### ISSUE TITLE
IndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by RadoBuransky** [JetBrains/intellij-scala#149]
This one might be difficult to investigate but I got this error right now.
**IntelliJ IDEA 14.1.3 build #IC-141.1010**
**Scala plugin v1.5**

```
0
java.lang.IndexOutOfBoundsException: 0
	at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:51)
	at scala.collection.immutable.List.apply(List.scala:83)
	at org.jetbrains.plugins.scala.lang.psi.ScalaPsiUtil$.forArgumentList$1(ScalaPsiUtil.scala:1912)
	at org.jetbrains.plugins.scala.lang.psi.ScalaPsiUtil$.parameterOf(ScalaPsiUtil.scala:1953)
	at org.jetbrains.plugins.scala.lang.psi.api.expr.ScArgumentExprList$class.parameterOf(ScArgumentExprList.scala:60)
	at org.jetbrains.plugins.scala.lang.psi.impl.expr.ScArgumentExprListImpl.parameterOf(ScArgumentExprListImpl.scala:18)
	at org.jetbrains.plugins.scala.codeInsight.intention.argument.PermuteArgumentsIntention$$anonfun$3.apply(PermuteArgumentsIntention.scala:40)
	at org.jetbrains.plugins.scala.codeInsight.intention.argument.PermuteArgumentsIntention$$anonfun$3.apply(PermuteArgumentsIntention.scala:40)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:284)
	at org.jetbrains.plugins.scala.codeInsight.intention.argument.PermuteArgumentsIntention.check(PermuteArgumentsIntention.scala:39)
	at org.jetbrains.plugins.scala.codeInsight.intention.argument.PermuteArgumentsIntention.isAvailable(PermuteArgumentsIntention.scala:22)
	at com.intellij.codeInsight.intention.PsiElementBaseIntentionAction.isAvailable(PsiElementBaseIntentionAction.java:64)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.isAvailableHere(ShowIntentionActionsHandler.java:125)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:106)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:294)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:150)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:293)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:212)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:188)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by niktrop** [comment]
Thanks for report.
That was an easy one :)

**Comment by RadoBuransky** [comment]
Thas was fast! Thanks
