### ISSUE TITLE
FileNotFoundException on try downloadIdea

### ISSUE THREAD

**Issue by Tolsi** [JetBrains/intellij-scala#194]
I try to follow the instructions for building plug-in and get this error:

```
/intellij-scala [idea15.x] $> sbt downloadIdea
[info] Loading project definition from /Volumes/Tolsi ExtHD/Code/intellij-scala/project
[info] Set current project to scalaCommunity (in build file:/Volumes/Tolsi%20ExtHD/Code/intellij-scala/)
[info] Downloading https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/142.4245.2/ideaIC-142.4245.2.zip to /Volumes/Tolsi ExtHD/Code/intellij-scala/SDK/ideaSDK/ideaIC-142.4245.2.zip
[info] Unpacking /Volumes/Tolsi ExtHD/Code/intellij-scala/SDK/ideaSDK/ideaIC-142.4245.2.zip to /Volumes/Tolsi ExtHD/Code/intellij-scala/SDK/ideaSDK/142.4245.2
[info] Downloading https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/142.4245.2/ideaIC-142.4245.2-sources.zip to /Volumes/Tolsi ExtHD/Code/intellij-scala/SDK/ideaSDK/142.4245.2/sources.zip
Error opening https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/142.4245.2/ideaIC-142.4245.2-sources.zip: java.io.FileNotFoundException: https://s3-eu-west-1.amazonaws.com/intellij-releases/com/jetbrains/intellij/idea/ideaIC/142.4245.2/ideaIC-142.4245.2-sources.zip
    at sbt.ErrorHandling$.translate(ErrorHandling.scala:11)
    at sbt.Using$$anonfun$urlInputStream$1.apply(Using.scala:81)
    at sbt.Using$$anonfun$urlInputStream$1.apply(Using.scala:81)
    at sbt.Using$$anon$3.open(Using.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.IO$.download(IO.scala:236)
    at com.dancingrobot84.sbtidea.Downloader$.download(Tasks.scala:113)
    at com.dancingrobot84.sbtidea.Downloader$.download(Tasks.scala:102)
    at com.dancingrobot84.sbtidea.Tasks$$anonfun$updateIdea$2.apply(Tasks.scala:27)
    at com.dancingrobot84.sbtidea.Tasks$$anonfun$updateIdea$2.apply(Tasks.scala:27)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at com.dancingrobot84.sbtidea.Tasks$.updateIdea(Tasks.scala:27)
    at com.dancingrobot84.sbtidea.Keys$$anonfun$projectSettings$8.apply(Keys.scala:87)
    at com.dancingrobot84.sbtidea.Keys$$anonfun$projectSettings$8.apply(Keys.scala:87)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: https://s3-eu-west-1.amazonaws.com/intellij-releases/com/jetbrains/intellij/idea/ideaIC/142.4245.2/ideaIC-142.4245.2-sources.zip
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1835)
    at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:90)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1432)
    at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1430)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessController.doPrivileged(AccessController.java:713)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1429)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
    at java.net.URL.openStream(URL.java:1038)
    at sbt.Using$$anonfun$urlInputStream$1$$anonfun$apply$2.apply(Using.scala:81)
    at sbt.Using$$anonfun$urlInputStream$1$$anonfun$apply$2.apply(Using.scala:81)
    at sbt.ErrorHandling$.translate(ErrorHandling.scala:11)
    at sbt.Using$$anonfun$urlInputStream$1.apply(Using.scala:81)
    at sbt.Using$$anonfun$urlInputStream$1.apply(Using.scala:81)
    at sbt.Using$$anon$3.open(Using.scala:65)
    at sbt.Using.apply(Using.scala:24)
    at sbt.IO$.download(IO.scala:236)
    at com.dancingrobot84.sbtidea.Downloader$.download(Tasks.scala:113)
    at com.dancingrobot84.sbtidea.Downloader$.download(Tasks.scala:102)
    at com.dancingrobot84.sbtidea.Tasks$$anonfun$updateIdea$2.apply(Tasks.scala:27)
    at com.dancingrobot84.sbtidea.Tasks$$anonfun$updateIdea$2.apply(Tasks.scala:27)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at com.dancingrobot84.sbtidea.Tasks$.updateIdea(Tasks.scala:27)
    at com.dancingrobot84.sbtidea.Keys$$anonfun$projectSettings$8.apply(Keys.scala:87)
    at com.dancingrobot84.sbtidea.Keys$$anonfun$projectSettings$8.apply(Keys.scala:87)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (scalaCommunity/*:updateIdea) Error opening https://www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/142.4245.2/ideaIC-142.4245.2-sources.zip: java.io.FileNotFoundException: https://s3-eu-west-1.amazonaws.com/intellij-releases/com/jetbrains/intellij/idea/ideaIC/142.4245.2/ideaIC-142.4245.2-sources.zip
[error] Total time: 58 s, completed 28.08.2015 11:08:09
```

**Comment by Alefas** [comment]
They changed extension from zip to jar. We will fix it in our download task.
But project should work as binaries already downloaded.
Sources you can download manually (if you need) and attach them (in any case you have to attach sources manually).
